import Head from 'next/head';
import Image from 'next/image';
import dynamic from 'next/dynamic';
import styles from '../styles/Home.module.css';

const DUMMYDATA = {
  data: [
    {
      id: 1,
      userName: 'John Doe',
      name: 'John Doe',
      email: 'JohnDoe@email.com',
      gender: 'male',
      register_date: '04-01-2004:17.50',
    },
    {
      id: 2,
      userName: 'Sarah Doe',
      name: 'Sarah Doe',
      email: 'SarahDoe@email.com',
      gender: 'female',
      register_date: '04-01-2004:17.50',
    },
    {
      id: 3,
      userName: 'Lexi ',
      name: 'Lexi Doe',
      email: 'LexiDoe@email.com',
      gender: 'female',
      register_date: '04-01-2004:17.50',
    },
    {
      id: 4,
      userName: 'Thor',
      name: 'Thor Doe',
      email: 'ThorDoe@email.com',
      gender: 'Male',
      register_date: '04-01-2004:17.50',
    },
    {
      id: 5,
      userName: 'Luna ',
      name: 'Luna Doe',
      email: 'LunaDoe@email.com',
      gender: 'female',
      register_date: '04-01-2004:17.50',
    },
  ],
};

export default function Home() {
  const Table = dynamic(() => import('../components/DataTable'));
  const listHeaderTable = [
    'UserName',
    'Name',
    'Email',
    'Gender',
    'Register Date',
  ];
  return (
    <div>
      {/* // create datatable components tailwindcss */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-5 h-screen bg-gray-100">
        <Table tableHead={listHeaderTable} tableBody={DUMMYDATA} />
      </div>
    </div>
  );
}
