import { useState, useEffect } from 'react';
import Head from 'next/head';
import DataTable from '../modules/DataTable';

export default function Home() {
  const [isSSR, setIsSSR] = useState(true);
  useEffect(() => {
    setIsSSR(false);
  }, []);
  return (
    <div>
      {/* // create datatable components tailwindcss */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!isSSR && <DataTable></DataTable>}
    </div>
  );
}
